name: facebook_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # imagenes svg
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/emojis/angry.svg
    - assets/emojis/heart.svg
    - assets/emojis/laughing.svg
    - assets/emojis/like.svg
    - assets/emojis/sad.svg
    - assets/emojis/shocked.svg
    - assets/wallpapers/1.jpeg
    - assets/wallpapers/2.jpeg
    - assets/wallpapers/3.jpeg
    - assets/wallpapers/4.jpeg
    - assets/wallpapers/5.jpeg
    - assets/wallpapers/6.jpeg
    - assets/users/1.jpg
    - assets/users/2.jpg
    - assets/users/3.jpg
    - assets/users/4.jpg
    - assets/users/5.jpg
    - assets/users/6.jpg
    - assets/publications/ferrari.jpeg
    - assets/publications/flutter.jpeg
    - assets/logos/facebook.svg
  fonts:
    - family: FacebookIcon 
      fonts:
        - asset: assets/icons/FacebookIcon.ttf 
