/// Flutter icons SystemIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SystemIcon
///      fonts:
///       - asset: fonts/SystemIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SystemIcon {
  SystemIcon._();

  static const _kFontFam = 'SystemIcon';
  static const String? _kFontPkg = null;

  static const IconData windows = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData macos = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
