include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
linter:
  rules: 
    # importaciones relativas
    prefer_relative_imports: true
    # preferir comillas simples
    prefer_single_quotes: true